import React from 'react'
import "./policyTerms.scss"

function Terms() {
    return (
        <div className="terms">
            <div className="box">
                <h2>Kwikstarter Terms of use</h2>
                <h5>KWIKSTARTER LAUNCHPAD</h5>
                <h5>Terms and Conditions of https://kwikstarter.org/ </h5>
                <h5>Last revised Date 27th May 2021</h5>
                <p>1. Introduction
These Terms and Conditions (herein referred as “these Terms”) govern the use and the conditions of https://kwikstarter.org/ website (herein referred as “website”), and the Services provided by KWIKSWAP PROTOCOL Limited (herein referred as “KWIKSTARTER” or “We” or “Us”), a company incorporated and registered under the laws of British Virgin Islands. These Terms constitute a binding and enforceable legal contract between KWIKSTARTER and its affiliates and subsidiaries worldwide and you, an end user of the Services (herein referred as “You” or “User”) in relation to the Services. You and KWIKSTARTER are referred to separately as “Party” and collectively as “Parties”.<br/>

By accessing, registering, using, or clicking on the Services, and information made available by KWIKSTARTER via the https://kwikstarter.org/, you hereby accept and agree to all the terms set forth herein.<br/>

You are strongly advised to carefully read these Terms as well as the provisions detailed in our Privacy Policy prior to using the website and our Services. By using the website and the Services in any capacity, you agree that: (i) You have read and familiarized yourself with these Terms; (ii) You understand these Terms; and (iii) You agree to be bound by these Terms when using the website. If You do not agree to these Terms, please do not access or use the website and the Services. <br/>

We reserve the right to modify or amend these Terms, the website, or any content on either one of the platforms from time to time, including for security, legal, or regulatory reasons, as well as to reflect updates or changes to the services or functionality of the website. You are advised to check these Terms periodically to ensure that you are cognizant of the current versions and comply with them. Users of the website and the Services are bound by these changes which will take immediate effect after the revised versions of these Terms have been published on the website or mobile application. Through your continued use of or interaction with the website, the Services, tools, and information made available on these platforms, you hereby agree to be bound by the provisions highlighted in the subsequent versions.<br/>

We will provide a notification on the website specifying that changes have been made to these Terms whenever they occur. By accepting the notification, You accept that we have provided you with sufficient notice of any changes. You should seek professional advice regarding any possible legal requirements you must comply with in relation to use of the website, and tools that related to participating in the Service provided by the KWIKSTARTER.<br/>
</p>
                <p>2. Definitions<br/>
                &quot;AML&quot; refers to Anti-Money Laundering.<br/>

“Allocation Round” refers to Round 1 of KWIKSTARTER fundraising project tokens allocation, which will be managed by the KWIKSTARTER tiered system.<br/>

&quot;Applicable Laws&quot; refers to acts, statutes, regulations, ordinances, treaties, guidelines, and policies issued by governmental organizations or regulatory bodies, including, but not limited to, the governing law stipulated under Laws of the British Virgin Islands.<br/>

“KWIKSTARTER Token” refers to a blockchain - based token which is issued, stored, transferred, transacted on the Binance Smart Chain Network. Users need to hold KWIKSTARTER Token to participate in any Services on the Platform including Staking or pre-sale of Project selected for the launchpad. <br/>

“BNB” refers to Binance Cryptocurrency which is required to pay transaction fees on the Binance Smart Chain network.<br/>

“BUSD” refers to a stable coin issued for the Binance ecosystem and backed by the U.S. Dollar having a pegged value at 1 BUSD = $1.00 USD. <br/>

&quot;CFT&quot; refers to Combating the Financing of Terrorism.<br/>

&quot;Confidential Information&quot; refers to any non-public, proprietary information or documents of or related to the User or KWIKSTARTER (whether in writing, orally or by any other means) by or on behalf of the User to KWIKSTARTER and which if disclose in tangible or intangible form is marked confidential (including in visual, oral, or electronic form) relating to Us or any other User that was previously a User, which is provided or disclosed through KWIKSTARTER (or to any employees or agents) in connection with the use or participate in KWIKSTARTER services.<br/>

&quot;Content&quot; refers to all content generated by KWIKSTARTER, including logos, identifying marks, images, illustrations, designs, icons, photographs, videos, text, any written or multimedia materials, services, advertisements, software, code, data, files, archives, folders, or available downloads on the KWIKSTARTER Platform. <br/>

“Cookie” refer to the small text files that are placed on your computer by the website that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owner of the site.<br/>

“KWIKSTARTER Platform” refers to the KWIKSTARTER website, or platform that facilitates token swaps, and where the KWIKSTARTER Project is officially launched, and makes available its native Tokens (“Pool”) to be distributed to the KWIKSTARTER users in the allocation rounds in order to be swapped for other crypto assets.<br/>

“FCFS Round” refers to First Come First Serve Round or Round 2 of the KWIKSTARTER fundraising project token allocation for the unsold IDO project tokens left from the Allocation Round.<br/>

&quot;Prohibited Jurisdictions&quot; specifically refer to the United States of America (including its territories, and dependencies, and any state of the United States), Botswana, Cambodia, Central African Republic, Cuba, Democratic People’s Republic of Korea, Ethiopia, Ghana, Iran, Iraq, Libya, Somalia, South Sudan, Sri Lanka, Syria, Sudan, Thailand, Trinidad and Tobago, Tunisia, Venezuela, Yemen.<br/>

“Project” refers to a KWIKSTARTER Project being launched for Initial Decentralized Offering (‘IDO’) event on KWIKSTARTER Platform.<br/>

“Services” refer to the services provided to the Users through the website, which include the accessibility to the new IDO token offered from each IDO fundraising project, staking service and other relevant services available through the Platform and all free trials and beta services made available by KWIKSTARTER, which may be subject to periodic revision.<br/>

“Staking or Stake” refers to the staking or deposit service in which the Users can delegate or deposit the User’s KWIKSTARTER Tokens in exchange for a share of Net Staking Rewards on the Platform.<br/>

&quot;Wallet(s)&quot; refers to a BEP-20 wallet which must be compatible with the Binance Smart Chain Network, such as MetaMask or Trust wallet.
</p>
                <p>3. General Provisions <br/>
3.1 Contractual Relationship<br/>
These Terms constitute a valid and binding agreement between You and KWIKSTARTER. The binding obligations stipulated in these Terms are enforceable.<br/>

3.2 Revision and Amendments
KWIKSTARTER reserves the right to revise, amend, or update any clauses and provisions stipulated in these Terms in its sole discretion at any time. KWIKSTARTER will notify the revision or amendment of such clauses or provisions by updating these Terms and specify the &apos;Last Revised Date&apos; displayed on a page of Terms and Conditions. Any revisions and updates on these Terms will be automatically effective upon their publication on the Platform, which includes the website. Therefore, your continuity of accessing or using KWIKSTARTER Platform, and Services will be deemed that you agree to have read, understood, and accepted all revised terms and provisions. If you do not agree on any revised or updated terms and provisions, you should immediately stop accessing or using our Services. You are encouraged to frequently and carefully review these Terms to ensure that you understand these Terms.<br/>

3.3 Privacy Policy
You acknowledge and confirm that you have read, understood, and agreed to provisions stipulated in the Privacy Policy, which will explain how KWIKSTARTER treats your information and protects your privacy when accessing or using the KWIKSTARTER Platform. <br/>

By using KWIKSTARTER Platform, you hereby agree that KWIKSTARTER may collect, use your information, and anonymised data pertaining to your use of the Services for analytics, trends’ identification, and purpose of statistics to further enhance the effectiveness and efficiency of the Services. <br/>

You hereby expressly authorise KWIKSTARTER to disclose any and all information relating to you in KWIKSTARTER’s possession to any law enforcement or government officials upon the request by the court order.

3.4 Links to and from the Website <br/>
3.4.1 You may, through hypertext or other computer links, gain access form the website to websites operated or made available, or otherwise licensed by persons other than us (“Third Party Services”). Such hyperlinks are provided for your convenience.<br/>
3.4.2 A link from Third Party Services does not mean that KWIKSTARTER endorses or approves the content on such website or does not mean KWIKSTARTER is an operator of that website. You understand that you are solely responsible for determining the extent to which you may use or rely upon any content at any other Third Party Services websites which you have accessed from the KWIKSTARTER website. KWIKSTARTER has no control over the content of these sites or resources and accept no reasonability for them or for any loss or damage that may arise from your use of them. <br/>
3.4.3 KWIKSTARTER assumes no responsibility for the use of, or inability to use, any Third Party Services’ software, other materials, or contents posted and/or uploaded on such website and we will have no liability whatsoever to any person or entity for any inaccuracy or incompleteness of such third-party content. All intellectual property rights in and to Third Party Services are property of the respective third parties.<br/>
3.5 Disclaimer for Accessibility of the Website and the Services <br/>
3.5.1 KWIKSTARTER website merely facilitates the Users accessibility to the IDO Project tokens and does not provide you with any warranty or representation whatsoever regarding its quality, value, specification, fitness for the purpose, completeness or accuracy of its technology or infrastructure of the tokens.<br/>
3.5.2 KWIKSTARTER will make all commercially reasonable attempts to facilitate information about the Project on the KWIKSTARTER Platform. However, you hereby acknowledge that KWIKSTARTER does not guarantee the accuracy, timeliness, or completeness of such information, and does not provide any warranty in connection with your use or reliance on such information. You agree that your use of the Project information will be at all your own risk. KWIKSTARTER will not be liable to you in any manner for the termination, interruption, delay, or inaccuracy of any Project information launched on the  KWIKSTARTER Platform.<br/>
3.5.3 To the extent permitted by applicable laws, the website and KWIKSTARTER Services are provided on an ‘AS IS’ and ‘AS AVAILABLE’ basis. KWIKSTARTER does not warrant that the features, and functions contained in the website and the Services will satisfy your preferences You hereby agree and acknowledge that your access and use of the website and the Services are at your own risk, and you will be liable for any responsibility, consequences that may arise out of or in connection with the usage or accessibility of the website and the Services. You expressly agree that KWIKSTARTER will have absolutely no liability in this regard.<br/>
3.5.4 You hereby agree and acknowledge that the website may contain links to a third-party website or services that are not owned or even controlled by KWIKSTARTER, thus KWIKSTARTER will hold no responsibility for the content or services, goods, or activities provided by such third-party website. You further agree that KWIKSTARTER has no liability directly or indirectly for any damage, loss, or consequence arising out of or in connection with the usage or reliance of any content, material, services available through the third-party website.<br/>
3.5.5 KWIKSTARTER reserves the right to limit the availability of the website to any person, geographic area, or jurisdiction we so desire and/or terminate your access to and use of the website and the Services, at any time and in our sole discretion.<br/>
3.5.6 KWIKSTARTER may, at our sole discretion, impose limits or restrictions on the use you make of the website. Further, for commercial, security, technical, maintenance, legal or regulatory reasons, or due to any breach of these Terms, we may withdraw the website or your access to the website and the Services at any time and without notice to You.<br/>
3.6 Information <br/>
You acknowledge that you are solely responsible for any submissions of all contents, remarks, suggestions, ideas, materials, feedbacks, or other information, including bug reports in relation to the Services provided through the website including any submission to our social media platforms such as Twitter and Telegram, and you, not us, have full responsibility for such submissions, including their accuracy, legality, reliability, appropriateness, originality, and copyright. We shall reply on the information you have provided and will not verify it. Notwithstanding the foregoing, we have the right to refuse to post, remove, edit, or abridge any submission for any reason and to freely use, copy, disclose, publish, display, or exploit such submission as we deem necessary without any payment of royalty, acknowledgement prior to consent, we may retain copies of all information materials relevant to the Service.
</p>
                <p>4. Intellectual Property <br/>
4.1 All present and future copyright, title, interests in and to the Services, registered and unregistered trademarks, design rights, unregistered designs, database rights and all other present and future intellectual property rights and rights in the nature of intellectual property rights that exist in or in relation to the use and access of the website and Services are owned by or otherwise licensed to KWIKSTARTER. Subject to your compliance with these Terms, KWIKSTARTER grants you a non-exclusive, non-sub license, and any limited license to merely use or access the website and the Services in the permitted hereunder.<br/>
4.2 Except as expressly stated in these Terms, nothing in these Terms should be construed as conferring any right in or license to KWIKSTARTER’s or any other third party’s intellectual rights.<br/>
4.3 If and to the extent that any such intellectual property rights are vested in you by operation of law or otherwise, you agree to do any and all such acts and execute any and all such documents as we may reasonably request in order to assign such intellectual property rights back to us.<br/>
4.4 You agree and acknowledge that all website content must not be copied or reproduced, modified, redistributed, used, created for derivative works, or otherwise dealt with for any other reason without being granted a written consent from KWIKSTARTER.<br/>
4.5 Third parties participating on the website may permit KWIKSTARTER to utilise trademarks, copyrighted material, and other Intellectual Property associated with their businesses. KWIKSTARTER will not warrant or represent that the content of the website does not infringe the rights of any third party.<br/>
</p>
                <p>5. Participation in the KWIKSTARTER Services<br/>
5.1 In order to avail access to the Services or participate in the KWIKSTARTER Platform, you may be required to go through KYC process as requested by each IDO fundraising project. Please refer to the Identification Verification through KYC/AML Process in Clause 6 for further information. <br/>
5.2 In term of Staking, you acknowledge and agree that KWIKSTARTER provides Staking Service to Users for purposes of delegating (also referred to as “stake” or “staking”) the User’s KWIKSTARTER Tokens in exchange for a share of Net Staking Rewards. You will provide the staking instruction to the KWIKSTARTER. Once the staking instruction is received, the system will record the instruction and you will not be able to cancel or edit the staking instruction. When the KWIKSTARTER Platform connect with your BEP-20 wallet, you will see your tier based on the numbers of KWIKSTARTER Tokens held in your wallet. The level of tier will affect the numbers of IDO tokens that you will receive, and KWIKSTARTER has neither responsibility nor liability in relation to the allocation of IDO tokens.  Since it will be entirely subject to the IDO fundraising project creator.  <br/>
KWIKSTARTER reserves the right to reject your participation in Staking, if you fail to fulfil to satisfy the identity verification requirements through the KYC process or commit any other suspicious activity while participating in the Services provided by KWIKSTARTER.<br/>
5.3 Tokens being stacked are limited to KWIKSTARTER Tokens only. Once you initiate staking, you will be put in the each Allocation Round of IDO fundraising project tokens event. The IDO tokens will be distributed to you based on the level of the tier you are classified.  In the conclusion of the Allocation Round of IDO, you will be able to join the FCFS Round for purchasing the unsold IDO tokens. 
You hereby acknowledge and agree that the estimated IDO tokens or reward yield displayed on the KWIKSTARTER Platform for each IDO fundraising project is an estimation. The actual amount of IDO tokens reward you will receive may not match or may lower than your estimation which will be subject to the reward compression or expression. You further hereby acknowledge that KWIKSTARTER cannot promise or guarantee the certain amount of the reward receiving from staking your KWIKSTARTER Tokens in order to engage in the IDO fundraising project event. You shall to go through, and study the medium article of each IDO fundraising project and fully understand the significant information and conditions prior to participate such IDO event such as the allocation date, the underlying technology, the features and functions of IDO project tokens. <br/>
5.4 In the event that you wish to unstake/withdraw your KWIKSTARTER Tokens and gain the reward, you will provide the unstaking instruction to the KWIKSTARTER Platform. You acknowledge and agree that when you unstake your KWIKSTARTER Tokens, the delivery of such KWIKSTARTER Tokens into your BEP-20 wallet will take 7 days and the timing may vary based on time of day of the unstake/withdraw instruction and execution. The amount of your unstaking KWIKSTARTER Tokens will not count towards your tier level for upcoming IDO fundraising projects. 
KWIKSTARTER will levy a withdrawing fee or minimum transaction in the form of BNB amount, which will vary and be subject to the amendment only at its sole discretion of KWIKSTARTER periodically. KWIKSTARTER will not be liable for any loss caused or alleged caused by timing differences and economic lost associated with the actual delivery of the KWIKSTARTER Tokens. <br/>
5.5 KWIKSTARTER reserves the right to amend any terms related to any specific Staking program at any time in its sole discretion. KWIKSTARTER will not be liable for any losses due to your misunderstanding of the Staking program terms and changes to such term’s rules. 
</p>
                <p>6. Identity Verification through KYC/AML Process <br/>
6.1 KWIKSTARTER is a permissionless and fully decentralised platform for token swaps. As a software development company, KWIKSTARTER has no role in enforcing KYC by default, however, we have a mandatory requirement for Identification Verification KYC tools for the IDO fundraising companies using KWIKSTARTER to enforce on their users, which IDO companies have to comply with the mandatory. KWIKSTARTER is implementing KYC tools into our launchpad through https://kycaid.com/. <br/>
6.2 The use of KYC/AML tools on KWIKSTARTER by IDO fundraising companies using the Services on KWIKSTARTER Platform is not the discretion of said entitles, and they must require you to complete KYC verification process before participating in any IDO fundraising project events. <br/>
6.3 Although KWIKSTARTER makes no warranty as to the merit, legality, or juridical nature of any IDO token, we nonetheless understand the need of IDO fundraising projects to require KYC/AML Verification on their token sale participants of Users. Therefore, KWIKSTARTER reserves the right:<br/>
6.3.1 at any time, to ask for your personal information, Name-Surname, Birthday,-e- mail address, nationality, location, government identification number (Identification Card/Passport number and Date of Identification Card/Passport issuing), telegram username, BEP-20 wallet address, and any KYC documentation with the liveness test that it deems necessary to determine the identity and location of a User, and reserves the right to restrict Service and payment until identity is sufficiently determined;<br/>
6.3.2 The liveness test shall mean taking a photo of your government identification with your phone or camera. Then, also take a photo of yourself (selfie of your face) holding your ID document and the paper you wrote on next to your face (not covering your face), the piece of paper shall write down the (1) KWIKSTARTER, (2) the current date, and (3) the last 4 characters of your wallet address”. If you have any questions, please find detail about KYC process here: https://kwikswap.medium.com/<br/>
6.3.3 to share the submitted KYC information and documentation to the third parties to verify the authenticity of submitted information, and the end user (you) agree to this by using the Service;<br/>
6.3.4 to reject the use of the Service that KWIKSTARTER has the reasonable ground to believe that they are found to be in violation of relevant and applicable AML/CFT laws and regulations, and to cooperate with the competent authorities or any investigation when and if necessary upon the valid request by the court order.<br/>
6.4 KWIKSTARTER expressly prohibits and rejects the use of the Service for any form of illicit activity, including money laundering, terrorist financing or trade sanctions violations, consistent with various jurisdictions’ laws, regulations and norms. To that end, the Service is not offered to individuals or entities on any Politically Exposed Persons (“PEP”) lists, or subject to any United States, European Union, or other global sanctions or watch lists. By using the Service, you represent that you are not on any such lists.<br/>
6.5 You fully acknowledge that your information and KYC documentation may be disclosed to government agencies or regulator upon the only valid request of the court order. Once you have decided to participate in any IDO fundraising event and start staking your KWIKSTARTER Tokens, you must ensure that all information provided to KWIKSTARTER is complete, accurate, and updated in a timely manner. KWIKSTARTER will rely on the information you provided and should there be any reasonable grounds to believe that the partial or the whole of your information provided to us is incomplete, or incorrect, or outdated, KWIKSTARTER reserves the right to send you a notice to demand correction, or to delete such information directly, and, as the case may be, to prohibit you to access to all or part of KWIKSTARTER website and the Services.<br/>
6.6 If KWIKSTARTER has the reasonable ground to believe that any user transacts or use the Services by using the digital currencies derived from any suspicious illegal activities, KWIKSTARTER shall be entitled to freeze/close/delete accounts as necessary. KWIKSTARTER will hold no liability to such users for any damage, or loss arising out of or in connection with this manner herein. Please note that any attempt to circumvent this Clauses will also result in a similar action.
</p>
                <p>7. KWIKSTARTER Tokens <br/>
7.1 KWIKSTARTER will issue a blockchain-based token called “KWIKSTARTER Token” on Binance Smart Chain Network. KWIKSTARTER Token is classified as the utility token designed to be used solely on the KWIKSTARTER Platform or on https://kwikstarter.org/ website.<br/>
7.1 Users who stake KWIKSTARTER Tokens in their wallets will be eligible to participate in IDO fundraising project event. <br/>
7.1 KWIKSTARTER Token is not considered as security of any kind, and it also does not carry any right to vote, manage or share in the KWIKSTARTER Platform. <br/>
7.1 KWIKSTARTER Token is neither money nor legal tender/currency, whether fiat or otherwise, and it does not carry any value whether it is intrinsic or assigned. <br/>
8.  Misuse of the https://kwikstarter.org/ website (“the website”)<br/>
8.1 In the event of any misuse and/or abuse of the website or breach any provision in these Terms, we reserve the right to block your access to the website and other until the matter is solved.<br/>
8.1 Use of the website for transmission, publication or storage of any material on or via the website which is in violation of any applicable laws or regulations or any third-party’s rights is strictly prohibited, including but not limited to the use of the website or the transmission, distribution, publication or storage any material on or via the website in a matter or for the purpose which infringes copyright, trademark, trade secret or other intellectual property rights, is obscene or harmful to minors or constitutes an illegal act or harassment, is libellous or defamatory, violates any privacy or data protections laws, is fraudulent or breaches any exchange control laws.<br/>
9. KWIKSTARTER Services <br/>
9.1 Representations and Warranties<br/>
You hereby agree to make the following representations and warranties for accessing to the website and the Services of KWIKSTARTER:

9.1.1 You have full capacity and authority under the application laws to agree and bind yourself to these Terms.<br/>
9.1.2 You are eighteen years of age or older.<br/>
9.1.3 You are not a citizen or a resident from the Prohibited Jurisdictions, and you do not have any relevant connection with any jurisdictions where we have prohibited services and access to the website.<br/>
9.1.4 You are aware and agree to comply with all applicable domestic and international laws, statutes, ordinances, and regulations applicable to your use of the website and the Services. Your use of the website and the Services are not for any unlawful or illegal purposes, including but not limited to the usage against the copyright laws, AML/CFT laws.<br/>
9.1.5 You are the exclusive owner of KWIKSTARTER Tokens and your other cryptocurrencies, including BNB held in your wallet. The tokens maintained in your wallets are not and will not be derived from money laundering, terrorist financing, fraud, or any other illegal activities under any applicable laws. You further hereby acknowledge and agree that KWIKSTARTER will not be responsible for actions taken by you that result in the loss or destruction of the value of the tokens and rewards you hold in the wallet.<br/>
9.1.6 You validly undertake any action or enter into any transaction with regard to these Terms. You are solely responsible for use of the website and the Services for all activities, or transactions that occur on or through your User account on KWIKSTARTER.<br/>
9.1.7 You will provide only accurate, complete, and up-to-date information and documents, if any, for the purposes of accessing or using or participating KWIKSTARTER Services on the KWIKSTARTER Platform. You will further agree to put your effort to ensure that the confidentiality of your personal or credential information, including your wallet address is restricted, and safely maintained to your device you use to access the website.<br/>
9.1.8 You will be acknowledged and agree that if you lose access to the wallet that you connected with the KWIKSTARTER Platform, KWIKSTARTER will not be able to help you recover these lost, or transfer IDO tokens or any KWIKSTARTER Tokens back to your wallet. It will be your solely responsibility to manage your, and private key. <br/>
9.1.9 You will be responsible for obtaining the data network access necessary to use the website. Your network&lsquo;s data and rates and fees may apply if you access or use the website from a wireless-enabled device, and you will be responsible for such rates and fees.<br/>
9.1.10 You will understand and be aware of risks associated with accessing or using or participating in KWIKSTARTER Services, and you will be fully liable at your own risk.<br/>
9.1.11 You will be aware that you are subject to tax regulations in the jurisdiction you reside in and will be fully responsible for filling or reporting any taxes and paying them as required by the Applicable Laws. KWIKSTARTER will not be liable to compensate you for your tax obligations or advise you in relation to your tax obligations. Any uncertainties and unpredictable matters in tax legislation with respect to any tokens may expose you to any unknown or unforeseeable tax implications associated with your holding of tokens and the use of KWIKSTARTER Services for which KWIKSTARTER will have no liability. Moreover, you will not hold KWIKSTARTER liable for any expenses or losses resulting from unknown or unforeseeable tax implications.<br/>
9.1.12 You will not breach any of the provisions stipulated in these Terms, the Privacy Policy, or any Applicable Laws in any relevant jurisdictions. <br/>
9.1.13 You will not use the website and the Services in one of any following manners, except as expressly permitted in these Terms, and the KWIKSTARTER discretion. 
You will not:

(a) infringe any propriety rights, including but not limited to copyrights, patents, trademarks, or trade secrets of KWIKSTARTER. <br/>

(b) use the website or the Services to transmit any data or send or upload any material or content that contains viruses, Trojan horses, worms, time-bombs, keystroke loggers, spyware, adware, or any other harmful programmes or similar computer code designed to adversely affect the operation of the website and the Services provided on the Platform. <br/>

(c) expressly or impliedly, use the website and the Services that is deemed unlawful, offensive, malicious, threatening, libellous, defamatory, obscene, or otherwise objectionable or violates these Terms, or any other party&lsquo;s intellectual property. <br/>

(d) modify, make any back-up or archival copies of the Platform or any part thereof including disassembling, and you will also not adapt, hack the website or modify another website to imply that it is associated with the website falsely.
<br/>
(f) crawl, scrape, or otherwise cache any content from the website, and you will agree not to use any automated data collection methods, data mining, robots, or scraping or any data gathering methods of any kind on the website.
<br/>
(g) use the website or any of its contents for advertising or soliciting, for any other commercial, political, or religious purpose, or to compete, either directly or indirectly with KWIKSTARTER.
<br/>
9.1.14 You will defend, indemnify, and not hold KWIKSTARTER, its affiliates, each of their respective employees, officers, directors, and representatives liable to and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorney&lsquo;s fees), arising out of or relating to any third-party claim concerning these Terms, or your use of KWIKSTARTER Services in violation of these Terms and applicable laws.<br/>
9.2 Each of the Representations and Warranties will survive and continue to have full force and effect after the execution of these Terms.<br/>
10. Risk Disclosure<br/>
By accessing or using or participating in KWIKSTARTER Services, you expressly acknowledge and assume the following risks:
<br/>
10.1 Risk of loss in value
Tokens or any digital currencies are not issued by any central banks or national, supra-national, or quasi-national organizations. They are also not backed by any hard assets or other credit. The value of tokens or any digital currencies is affected by several factors, including but not limited to, the total number of tokens or any digital currencies in existence, the continued willingness of market participants to exchange government-issued currency for tokens or digital currencies , purchasers&lsquo; expectations with respect to the rate of inflation of fiat currencies, purchasers&lsquo; expectations with respect to the rate of deflation of cryptocurrencies, interest rates, currency exchange rates, cyber theft of cryptocurrencies from online digital wallet providers, or news of such theft from such providers or individuals&lsquo; digital wallets, investment and trading activities of large investors, monetary policies of the governments, trade restrictions, currency devaluations and revaluations, regulatory measures, the global or regional political, economic or financial events and situations. Thus, all these factors will affect the value of tokens or digital currencies, which may result in the permanent partial or total loss of the value of a particular tokens or digital currencies. No one will be obliged to guarantee the liquidity or the market price of any of the tokens or digital currencies maintained into your wallets. The volatility and unpredictability of the value of tokens or digital currencies relative to the government-issued currency may result in a significant loss over a short period of time.<br/>

10.2 The regulatory regime governing tokens or digital currencies
The regulatory framework relating to tokens or digital currencies remains unsettled, and any laws, regulations, or guidelines may be significantly revised and amended which will materially and adversely affect the value of tokens or digital currencies and your services on https://kwikstarter.org/ website or KWIKSTARTER Platform as follows.<br/>

10.3 Technical and System Failure affected the obligations stipulated in these Terms KWIKSTARTER may experience system failures, unplanned interruptions in its Binance Smart Chain Network or services, hardware or software defects, security breaches or other causes that could adversely affect the KWIKSTARTER infrastructure network, which includes https://kwikstarter.org/ website and KWIKSTARTER Platform.
KWIKSTARTER is unable to anticipate the occurrence of hacks, cyber-attacks, mining attacks, including but not limited to double-spend attacks, majority mining power attacks and selfish-mining attacks, distributed denial of service attacks or errors, vulnerabilities or defects in the website, KWIKSTARTER Tokens, Users&lsquo; wallets or any technology, including but not limited to smart contract technology. Also, KWIKSTARTER is unable to detect the hacks as mentioned earlier, mining attacks, cyber-attacks, distributed denials of service errors vulnerabilities, or defects in a timely manner and does not have sufficient resources to efficiently cope with multiple service incidents happening simultaneously or in rapid succession. <br/>

In addition, KWIKSTARTER&lsquo;s network or services could be disrupted by numerous events, including natural disasters, equipment breakdown, network connectivity downtime, power losses, or even intentional disruptions of its services, such as disruptions caused by software viruses or attacks by unauthorized users, some of which are beyond KWIKSTARTER&lsquo;s control. Although KWIKSTARTER has taken steps and used its best endeavour against malicious attacks on its appliances or its infrastructure, which are critical for the maintenance of the KWIKSTARTER Platform and its services, there can be no assurance that cyber-attacks, such as distributed denials of service, will not be attempted in the future, and that KWIKSTARTER&lsquo;s enhanced security measures will be effective. Any significant breach of KWIKSTARTER&lsquo;s security measures or other disruptions resulting in a compromise of the usability, stability and security of KWIKSTARTER&lsquo;s network or services, including the KWIKSTARTER Platform, may adversely affect KWIKSTARTER Tokens.

10.4 KWIKSTARTER will have no liability for any delay, error, interruption, or failure to perform any obligation under these Terms where the delay or failure is directly or indirectly resulting from any causes beyond KWIKSTARTER&lsquo;s control, including, but not limited to:<br/>
10.4.1 Acts of God, nature, or court of government;<br/>
10.4.2 Failure or interruption of public or private telecommunication networks, the failure of Binance Smart Chain Network, communication channels or information systems;<br/>
10.4.3 Acts or omission of acts of a party for whom We are not responsible;<br/>
10.4.4 Delay, failure, or interruption in, or unavailability of, third-party services;<br/>
10.4.5 Strikes, lockouts, labour disputes, wars, terrorist acts and riots.<br/>
10.5 YOU UNDERSTAND AND AGREE THAT YOUR USE OF KWIKSTARTER SERVICES AND THE WEBSITE IS COMPLETELY AT YOUR OWN RISK. THIS CLAUSE IS NOT EXHAUSTIVE AND DOES NOT DISCLOSE ALL THE RISKS ASSOCIATED WITH DIGITAL CURRENCIES AND THE USE OF SERVICES. THEREFORE, YOU ARE RECOMMENDED TO CAREFULLY CONSIDER WHETHER SUCH USE IS SUITABLE FOR YOU IN LIGHT OF YOUR JUDGEMENT, CIRCUMSTANCES, AND FINANCIAL POSITION.<br/>
11. Limitation of Liability<br/>
11.1 NOTWITHSTANDING ANY PROVISIONS WITHIN THESE TERMS, IN NO EVENT WILL KWIKSTARTER, ITS AFFILIATES, OR ITS EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE TO THE USER FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEBSITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE WEBSITE OR OTHER SUCH WEBSITES, OR ANY OTHER SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE, OR OTHER SUCH WEBSITES, INCLUDING, BUT NOT LIMITED TO, LOST REVENUE, LOST PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, LOSS OF YOUR CREDENTIAL INFORMATION, LOSS OR INTERRUPTION OF TECHNOLOGY, LOSS OF USE OF SERVICE OR EQUIPMENT, EVEN IF THE USER WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND WHETHER ARISING UNDER A THEORY OF CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE. KWIKSTARTER WILL ALSO HAVE NO LIABILITY FOR ANY EMERGENCY AND/OR UNFORESEEABLE INCIDENTS RELATED TO YOUR USE OF KWIKSTARTER SERVICES ON THE KWIKSTARTER PLATFORM SUCH AS STOLEN PRIVATE KEY, OR HACKED ACCOUNTS. <br/>
11.2 Except as expressly provided in these Terms, and to the maximum extent permitted by any Applicable Laws, we disclaim all other representations or warranties, express or implied, made to you, your affiliates, or any other person, including, without limitation, any warranties regarding the quality, suitability, merchantability, fitness for a particular purpose or otherwise (regardless of any course of dealing, custom or usage of trade) of any service provided incidental to KWIKSTARTER Services under these Terms.<br/>
In no event will our aggregate liability for any loss or damage that arises in connection with KWIKSTARTER Services exceed the purchase amount you paid to participate in the KWIKSTARTER Platform, if any, during a twelve (12) month period immediately preceding the event that gave rise to the claim for liability. The preceding limitations of liability will apply to the fullest actual amount you paid to participate or access in the KWIKSTARTER Platform..

11.3 Except as expressly provided in these Terms, and to the fullest extent permitted by any Applicable Laws, KWIKSTARTER, its affiliates, and their related parties each disclaim all liability to you for any loss or damage arising out of or due to:<br/>
11.3.1   your use of, inability to use, or availability or unavailability of the Services, including any third party services made available through the Services;<br/>
11.3.2   the occurrence or existence of any defect, interruption, deletion of files, delays in the operation or transmission of information to, from, or through the Services, communications failure, theft, destruction or unauthorised access to KWIKSTARTER’s records, programs, services, server, or other infrastructure relating to the Services;<br/>
11.3.3 the Services being infected with any malicious code or viruses; or<br/>
11.3.4 the failure of the Services to remain operational for any period of time.<br/>
12. Indemnification
You irrevocably undertake the responsibility of fully indemnifying and holding harmless each of KWIKSTARTER, its affiliates, licensors, shareholders, officers, directors, managers, employees, and agents from and against any and all losses, claims, actions, proceedings, damages, demands, judgements, sums, liabilities, damages, costs, charges and expenses, including, but not limited to, any reasonable attorney&lsquo;s fees or penalties imposed by any regulatory authority, and reimbursements arising out of or related to the following situations:

12.1 Your use or any person using the Services on your behalf or participation in accordance with KWIKSTARTER Services on the website or the KWIKSTARTER Platform;<br/>
12.2 Your breach of or our enforcement of these Terms;<br/>
12.3 Any violations of Applicable Laws, regulation, or rights of any third-party during your use or participate in KWIKSTARTER Platform.<br/>
If you are obligated to indemnify KWIKSTARTER, its affiliates, shareholders, licensors, officers, directors, managers, employees, and agents, KWIKSTARTER will have the right, at our sole discretion, to control any action or proceeding and to determine whether KWIKSTARTER wishes to proceed, or settle, and if so, on what terms or provisions.

13. Termination<br/>
13.1 These Terms will be immediately terminated by discontinuing your use, or participate in KWIKSTARTER Services and you agree to terminate the accessibility on the Platform.<br/>
13.2 These Terms can be suspended or terminated without a notice from us if there is a reasonable ground to believe that you have breached any of the terms or provisions stipulated in these Terms, or if you do not comply with these Terms. <br/>
13.3 The termination of these Terms will not prevent KWIKSTARTER from seeking remedies from you in the case where you breach any terms or provisions before such termination. KWIKSTARTER will not be liable to you or to any third party for any termination, suspension, or modification of your access to the Services.<br/>
13.4 Any ongoing obligation to you as well as the provisions regarding (i) KWIKSTARTER&lsquo; Intellectual Property, (ii) No solicitation or Offering, (iii) indemnification, (iv) Limitation of liability, and (v) any other provisions designed to survive, will survive any termination or expiration of these Terms for any reason.<br/>
14. No Financial and Legal Advice<br/>
KWIKSTARTER is merely a technology platform, and we are not your broker, intermediary, agent, or legal advisor and has no fiduciary relationship or obligation to you in connection with any decisions or activities effected by you using or participating on the website or the BSCPAAD Platform. No communication or information provided to you by KWIKSTARTER is intended as or will be considered or construed as, the solicitation of an offer to buy, the investment advice, financial advice, legal advice, or any other sort of advice. All Services, Transactions, and Investments will be executed automatically based on the parameters of your consideration. You will be solely responsible for determining whether any services, or investments are suitable and match your interests according to your judgement, objectives, circumstances and risk tolerance. You will be solely responsible for any losses or liabilities therefrom.

Before executing any transactions, purchasing KWIKSTARTER Tokens or IDO tokens on the KWIKSTARTER Platform, you should consult with your independent financial, legal, or tax professionals. KWIKSTARTER will not be liable for the decisions you make to access and purchase through the KWIKSTARTER. 
<br/>
15. Notice/Announcement
Any notice, requests, demands, and determinations for KWIKSTARTER under these Terms (other than routine operational communications) shall be sent to info@Kwikstarter.com at https://kwikstarter.org/.
<br/>
16. Governing Law, Resolving Disputes, Arbitration and Class Action Waiver
PLEASE READ THIS SECTION CAREFULLY AS IT INVOLVES A WAIVER OF CERTAIN RIGHTS TO BRING LEGAL PROCEEDINGS, INCLUDING A CLASS ACTION.
<br/>
16.1 Notice of Claim and Dispute Resolution Period
Please contact KWIKSTARTER first. KWIKSTARTER will seek to address your concerns without resorting to formal legal proceedings whenever possible. If you have a dispute with KWIKSTARTER, you should contact KWIKSTARTER, and a case number will be assigned. KWIKSTARTER will attempt to resolve your dispute internally as soon as possible. The parties will agree to negotiate in good faith to resolve the dispute and discussions will remain confidential and subject to applicable laws protecting settlement discussions from use as evidence in any legal proceeding.
<br/>
16.2 Agreement to Arbitrate
You and KWIKSTARTER agree that subject to paragraph 16.1 above, any dispute, claim, or controversy between you and KWIKSTARTER that arises in connection with, or relating in any way, to these Terms, or to your relationship with KWIKSTARTER as a user of KWIKSTARTER Services (whether by contract, tort, statute, fraud, misrepresentation, or any other legal theory, and whether the claims arise during or after the termination of these Terms) will be determined by a mandatory final and binding individual arbitration rather than a class action, except as set forth below under Exceptions to the Agreement to Arbitrate. You and KWIKSTARTER further agree that the arbitrator will have the exclusive power to rule on his or her jurisdiction, including, without limitation, any objections with respect to the existence, scope, or validity of the Agreement to Arbitrate, or to the arbitrability of any claim or counterclaim. Arbitration is more informal than a lawsuit in court. THERE IS NO JUDGE OR JURY IN ARBITRATION, AND COURT REVIEW OF AN ARBITRATION AWARD IS LIMITED. There may be more limited discovery than in court. The arbitrator must follow this agreement and can award the same damages and relief as a court, including, if applicable, attorney fees, except the arbitrator may not award declaratory or injunctive relief benefiting anyone but the parties to the arbitration. The arbitration provisions set forth in this Section will survive termination of these Terms. 
<br/>
16.3 Arbitration Rules
 Any dispute arising out of or in connection with these Terms including any question regarding its existence, validity or termination, shall be referred to and finally resolved by arbitration administered by the Singapore International Arbitration Centre (“SIAC”) in accordance with the Arbitration Rules of the Singapore International Arbitration Centre (&quot;SIAC Rules&quot;) for the time being in force, which rules are deemed to be incorporated by reference in these Terms. The seat of the arbitration shall be Singapore. The Tribunal shall consist of one arbitrator. The language of the arbitration shall be English. 
 <br/>
16.4 Governing Law/Jurisdiction
 The governing law of the arbitration will be that of the British Virgin Islands.
 <br/>
16.5 Confidentiality.
The parties agree that the arbitration will be kept confidential. The existence of the arbitration, any non-public information provided in the arbitration, and any submissions, orders or awards made in the arbitration will not be disclosed to any non-parties except the tribunal, the parties, their counsel, experts, witnesses, accountants and auditors, insurers and reinsurers, and any other person necessary to facilitate the arbitration. Notwithstanding the preceding, a party may disclose information to the extent that disclosure may be required to fulfil a legal duty, protect, or pursue a legal right, or enforce or challenge an award in bona fide legal proceedings. This confidentiality provision will survive the termination of these Terms and any arbitration brought under these Terms.
<br/>
16.6 Class Action Waiver
You and KWIKSTARTER agree that any claims relevant to these Terms, or your relationship with KWIKSTARTER will be brought against the other party in arbitration on an individual basis only and not as a plaintiff or class member in a purported class or representative action. You and KWIKSTARTER further agree to waive any right for such claims to be brought, heard, or arbitrated as a class, collective, representative, or private attorney general action, to the extent permissible by applicable laws. Combining or consolidating individual arbitrations into a single arbitration is not permitted without the consent of all parties involved. 
<br/>
16.7 KWIKSTARTER reserves the right to update, modify, revise, suspend, or make future changes to Section 16.2 regarding the parties&lsquo; Agreement to Arbitrate, subject to applicable laws. You hereby consent and agree that it is your responsibility to ensure that your understanding of this Clause is up to date. Subject to applicable laws, your continued use of your KWIKSTARTER account will be interpreted as your acceptance of any modifications to Clause 16 regarding the parties&lsquo; Agreement to Arbitrate. You agree that if you object to the modifications to Clause 16, KWIKSTARTER may block access to your account pending closure of your account. In such circumstances, these Terms prior to modification will remain in full force and affect the pending closure of your accessibility.<br/>
17. Miscellaneous<br/>
17.1 Severability
If any of the provisions in these Terms is found by a court of competent authority to be invalid, void, unlawful or unenforceable under any applicable laws, such unenforceability or invalidity will not render these Terms unenforceable or invalid as a whole, and such provisions will be deleted without affecting the remaining provisions herein.
<br/>
17.2 Variation of Terms
KWIKSTARTER has the right to revise these Terms at our sole discretion at any time, and by using the website or other KWIKSTARTER Platform, you will be expected to review such Terms regularly to ensure that you understand all provisions stipulated in these Terms.
<br/>
17.3 Assignment
KWIKSTARTER will be allowed to assign, transfer, and subcontract Our rights and/or obligations under these Terms without the need to provide you any notification or acquire your consent. Nevertheless, you will not be permitted to assign, transfer, or subcontract any of your rights and/or obligations under these Terms.
<br/>
17.4 Entire Agreement
These Terms, including the Privacy Policy and any rules contained on the website or others KWIKSTARTER Platform, constitute the sole and entire agreement between You and KWIKSTARTER with respect to your use of the KWIKSTARTER Platform, and supersedes other prior or contemporaneous negotiations, discussions, agreements, understandings, representations, and warranties, both written and oral, between You and KWIKSTARTER with respect to such subject matter.
<br/>
17.5 No Third-Party Rights
Nothing in these Terms will be deemed to create any rights to any creditors or other persons, not a party hereto. Moreover, these Terms will not be construed, in any respect, to be a contract, in whole or in part, for the benefit of any third parties.
<br/>
17.6 Clickwrap
KWIKSTARTER may deliver the Service through electronic means such as download links, graphical, Tools or other technologies for providing the Service for users. The user interfaces to such electronic means may require that the users agree to these Terms by checking a box, clicking a button, or continuing with the Service. If user through such action the user becomes a Party to these Terms. Such an action of acceptance shall be sufficient to bind the users to the terms and conditions herein these Terms. 

17.7 Waiver<br/>
The failure of one Party to require the performance of any provision will not affect that Party&lsquo;s right to require performance at any time thereafter. At the same time, the waiver of one Party to seek recovery for the other Party&lsquo;s violation of these Terms of any provisions of applicable terms will not constitute a waiver by that Party of any subsequent breach or violation by the other Party or of the provision itself.
<br/>
Copyright © 2021. All Rights Reserved by Kwikstarter
Privacy Policy Terms of Use

</p>
            </div>

            <div className="box">
                <h2>Kwikstarter Staking Policy</h2>
                <h5>Kwikstarter IDO Launchpad</h5>
                <h5>Staking Policy of https://kwikstarter.org</h5>
                <h5>Last revised Date 27th May 2021</h5>
                <p>Staking Policy <br/>
Kwikstarter provides Staking Service to Users for purposes of delegating (also referred to as “stake” or “staking”) the User’s Kwikswap tokens in exchange for a share of Net Staking Rewards. You can provide instructions, such as delegate and undelegate through the Platform. Once the instructions are received, the system will record the instructions and you will not be able to cancel or edit those instructions. You acknowledge and agree that Kwikstarter holds the right to reject your participation in Staking, in the event that you are unable to fulfill your identity verification requirements or for any other suspicious activity detected while participating in the services provided by Kwikstarter. The Tokens being staked are limited to tokens to Kwikswap tokens only. You acknowledge and agree that the estimated reward yield displayed on Kwikstarter is an estimation and not a guaranteed or promised actual yield. The actual yield you receive may not meet or may be lower than the estimated yield and subject to yield compression or expansion. Kwikstarter does not promise or guarantee the actual yield or Staking rewards you will receive. You acknowledge and agree that when you undelegate your Tokens, the delivery of such Tokens into your BEP-20 compatible wallet is 7 days and the timing may vary based on time of day of request and execution. Kwikstarter may levy a withdrawal fee or minimum transaction amount at its sole discretion and vary from time-to-time. KWIKSTARTER as shall not be liable for any losses caused by timing differences associated with the actual delivery of the Tokens. You acknowledge and agree that Kwikstarter reserves the right to amend any terms related to any specific Staking program at any time in its sole discretion. Kwikstarter shall not be liable for any losses due to your misunderstanding of the Staking program terms and changes to such term’s rules
</p>
            </div>
            <div className="box">
                <h2>Kwikstarter Clickwrap Acceptance</h2>
                <h5>Kwikstarter IDO Launchpad</h5>
                <h5>Clickwrap Acceptance of https://kwikstarter.org</h5>
                <h5>Last revised Date 27th May 2021
                    <br/>
                    Clickwrap Acceptance
                </h5>
                <p>By clicking on the “I Agree” button below, I acknowledge that I have read the [Terms and Conditions] and [Privacy Policy], and that I agree to their terms. I understand that the Privacy Policy contain Cookie Policy. 
        <br/>
We use cookies to personalise content and to provide you with an improved user experience. By continuing to browse this site you consent to the use of cookies. You can find out more in our privacy policy and Cookie Policy, and manage the choices available to you at any time by following the instruction of your device preferences.
<br/>
[  ] I AGREE, and continue with the Service
</p>
            </div>
        </div>
    )
}

export default Terms
